modules_dir = "artifacts/"

[[module]]
    name = "composedb_adapter"
    max_heap_size = "500 Kib"
    logger_enabled = true

[[module]]
    name = "facade"
    # logger_enabled = true

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }



