services:
  cdb2_fluence: # 
    command: -c /.fluence/v1/Config.toml -f ed25519 -m ${MANAGEMENT-KEY} -t 7771 -w 9991 
    container_name: cdb2_fluence
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_i>
      WASM_LOG: info
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: /ip4/${IP}/tcp/25001
      FLUENCE_ENV_AQUA_IPFS_LOCAL_API_MULTIADDR: /dns4/cdb2_ceramic-ipfs/tcp/5001
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_SWARM_MULTIADDR: /ip4/{IP}/tcp/24001
      CERAMIC_HOST: /dns4/cdb2_ceramic-sidecar/tcp/7007
    image: fluence-composedb
    build:
       context: .
       dockerfile: ./composedb.dockerfile
    ports:
      - 7771:7771
      - 9991:9991
      - 28081:8080 # /metrics
      - 25001:5001
      - 24001:4001
    restart: unless-stopped
    volumes:
      - ./config.toml:/.fluence/v1/Config.toml
      - cdb2-fluence:/.fluence
    networks:
      - cdb2

  cdb2_composedb-server:
    image: composedb-server-nodejs
    container_name: net2_composedb-server
    build:
      context: .
      dockerfile: ./composedbserver.dockerfile
    restart: unless-stopped
    volumes:
      - ./composites:/opt/composites
    networks:
      - cdb2

  cdb2_ceramic-ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    container_name: net2_ceramic-ipfs
    environment:
      CERAMIC_NETWORK: "testnet-clay"
    ports:
      - 8081:8080
      - 4002:4001
      - 5002:5001
    networks:
      - cdb2
    restart: unless-stopped

  cdb2_ceramic-sidecar:
    image: ceramic-sidecar
    container_name: net2_ceramic-sidecar
    build:
       context: .
       dockerfile: ./ceramic-alt.dockerfile
    command: ceramic daemon --network=testnet-clay --config=/root/.ceramic/daemon.config.json
    environment:
      CERAMIC_ENABLE_EXPERIMENTAL_COMPOSE_DB: "true"
    ports:
      - 17007:7007
    volumes:
      - ./ceramic_logs:/root/.ceramic/logs
      - cdb2-ceramic:/root/.ceramic/statestore
    networks:
      - cdb2

version: "3.5"
volumes:
  cdb2-fluence: null
  cdb2-ceramic: null

networks:
  cdb2: null