services:
  fluence:
    command: -f ed25519 -m ${MANAGEMENT_KEY} -t 7770 -w 9990 
    container_name: cdb${N}_fluence
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_i>
      WASM_LOG: info
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: /ip4/${IP}/tcp/500${N}
      FLUENCE_ENV_AQUA_IPFS_LOCAL_API_MULTIADDR: /ip4/127.0.0.1/tcp/5001 
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_SWARM_MULTIADDR: /ip4/${IP}/tcp/400${N}
    image: fluencelabs/fluence:ipfs_v0.0.65_67
    ports:
      - 777${N}:7770 # tcp
      - 999${N}:9990 # ws
      - 500${N}:5001 
      - 400${N}:4001
    restart: unless-stopped
    volumes: 
      - fluence:/.fluence
    networks:
      - cdb

  composedb:
    image: composedb-server-nodejs
    container_name: cdb${N}_composedb
    build:
      context: .
      dockerfile: ./composedbserver.dockerfile
    restart: unless-stopped
    volumes:
      - ./.env${N}:/opt/composedb-server/.env
      - composites:/opt/composites
    networks:
      - cdb

  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    container_name: cdb${N}_ipfs
    environment:
      CERAMIC_NETWORK: "testnet-clay"
    ports:
      - 401${N}:4001 # swarm tcp
    healthcheck:
      test: [ "CMD-SHELL", "ipfs cat QmWATWQ7fVPP2EFGu71UkfnqhYXDYH566qy47CnJDgvs8u" ]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ipfs:/data/ipfs 
    networks:
      - cdb
    restart: unless-stopped

  ceramic:
    image: ceramicnetwork/js-ceramic:2.16.0
    container_name: cdb${N}_ceramic
    command: echo "export CERAMIC_ENABLE_EXPERIMENTAL_COMPOSE_DB=true" >> .bashrc && ceramic daemon --network=testnet-clay --config=/root/.ceramic/daemon.config.json
    environment:
      CERAMIC_ENABLE_EXPERIMENTAL_COMPOSE_DB: "true"
    volumes:
      - ./daemon.config_${N}.json:/root/.ceramic/daemon.config.json 
      - ./ceramic_logs:/root/.ceramic/logs
      - ceramic:/root/.ceramic/statestore
    depends_on:
      ipfs:
        condition: service_healthy
    networks:
      - cdb

version: "3.5"
volumes:
  fluence:
    name: cdb${N}-fluence
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/drive-blue/transport-union/fluence-composedb/cdb${N}-fluence'
    
  ceramic:
    name: cdb${N}-ceramic
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/drive-blue/transport-union/fluence-composedb/cdb${N}-ceramic'

  ipfs: 
    name: cdb${N}-ipfs
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/drive-blue/transport-union/fluence-composedb/cdb${N}-ipfs'

  composites: 
    name: cdb${N}-composites
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/drive-blue/transport-union/fluence-composedb/cdb${N}-composites'

networks:
  cdb:
    name: cdb${N}