
modules_dir = "../artifacts/"


[[module]]
    name = "curl_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "composedb_adapter"
    max_heap_size = "500 Kib"
    logger_enabled = true

    [module.mounted_binaries]
    tu_cdb = "/usr/bin/tu-cdb"

[[module]]
    name = "tu_cdb_demo"
    # logger_enabled = true




