[package]
name = "ipfs_adapter"
version = "0.1.0"
authors = ["Transport Union"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "ipfs_adapter"

[dependencies]
marine-rs-sdk = { version = "=0.6.10", features = ["logger"]}
log = "0.4.8"
serde_json = "1.0.64"
