[package]
name = "tu-cdb-demo"
version = "0.1.0"
authors = ["Joera <joeramulders@gmail.com>"]
edition = "2018"

[[bin]]
name = "tu_cdb_demo"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.15"

[dev-dependencies]
marine-rs-sdk-test = "0.5.0"
